### ISSUE TITLE
ValueError: All-NaN slice encountered

### ISSUE THREAD

**Issue by saisugash-senthil** [meilfang/SynthASpoof#4]
On running the test script as per the format provided in the README:
`python test.py \
  --test_csv 'test_data.csv' \
  --model_path 'model.pth'`
  
  I'm getting the error message:
  `np.abs(differ_tpr_fpr_1) [nan nan nan nan nan nan nan nan nan]
Traceback (most recent call last):
  File "C:\Users\ssais\Documents\AntiSpoofing_Githubrepos\SynthASpoof\test.py", line 94, in <module>
    main(test_csv=args.test_csv, args=args)
  File "C:\Users\ssais\Documents\AntiSpoofing_Githubrepos\SynthASpoof\test.py", line 29, in main
    AUC, HTER = test_model(model, test_loader)
  File "C:\Users\ssais\Documents\AntiSpoofing_Githubrepos\SynthASpoof\test.py", line 62, in test_model
    AUC, _, _, HTER = performances_cross_db(raw_test_scores, gt_labels)
  File "C:\Users\ssais\Documents\AntiSpoofing_Githubrepos\SynthASpoof\utils.py", line 75, in performances_cross_db
et_err_threhold_cross_db
    right_index = np.nanargmin(np.abs(differ_tpr_fpr_1))
  File "C:\Users\ssais\Documents\AntiSpoofing_Githubrepos\SynthASpoof\env\lib\site-packages\numpy\lib\nanfunctions.py", line 552, in nanargmin
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered
`
The issue seems to be with the fact that either `fpr` or `tpr` is a list with all-Nan values, due to which the values of `np.abs(differ_tpr_fpr_1)` is `[nan nan nan nan nan nan nan nan nan]` (I printed it out as a debugging measure). Please do provide the solution to this issue.

**Comment by saisugash-senthil** [comment]
The issue seems to be with the line `fpr, tpr, threshold = roc_curve(gt_labels, prediction_scores, pos_label=pos_label) ` under the function `performances_cross_db(prediction_scores, gt_labels, pos_label=1, verbose=True)` in the 'utils.py' script. In my case, 
gt_labels is a list containing only zeros. gt_labels, has been generated from the `raw_test_scores, gt_labels, _ = compute_video_score(raw_test_video_ids, raw_test_scores, gt_labels)` line from test.py. Here's the entire function for reference:
```
def compute_video_score(video_ids, predictions, labels):
    predictions_dict, labels_dict = defaultdict(list), defaultdict(list)

    for i in range(len(video_ids)):
        video_key = video_ids[i]
        predictions_dict[video_key].append(predictions[i])
        labels_dict[video_key].append(labels[i])
    # print("predictions_dict: ",predictions_dict)
    new_predictions, new_labels, new_video_ids = [], [], []
    print("labels_dict: ",labels_dict)
    for video_indx in list(set(video_ids)):
        new_video_ids.append(video_indx)
        scores = np.mean(predictions_dict[video_indx])
        label = labels_dict[video_indx][0]
        new_predictions.append(scores)
        new_labels.append(label)
```
        
In my case, labels_dict is a dictionary where the value of each corresponding key is [0.0,1.0]. The element in the 0th index (which is always 0.0) of this dictionary is being appended to new_labels, which is gt_labels after being instantiated. This causes gt_labels to be a list with all the elements to be 0s and hence the issues I mentioned in the previous comment. Another piece of info that I would like to mention is the fact that my test.csv looks something like this:
       
![image](https://github.com/meilfang/SynthASpoof/assets/128836949/5b63ea3f-0d0a-42e7-958f-dab5f92ef189)

It has alternating images that are 'bonafide' and 'attack'. However, this does not mean that every pair of bonafide and attack images are of the same person, they are bonafide and attack images of different people. The bonafide image of one person may be paired with the attack image of another person, and the attack image of the first person maybe paired with the bonafide image of some other person.

Do let me know if there is an issue with the way I have generated the above test.csv file.

Thank You.
